### PR TITLE
Ltc spousal allocation

### PR DESCRIPTION
**Pull request by IlseFerris**
1. Added cancel_confirmation to both dialogs.  
2. Updated spousal allocation determination screen to code correctly if income from spouse is "other retirement".  This is code 17 on UNEA, code 15 on the spousal allocation determination screen.  The script now changes this code to a 15 on spousal allocation determination screen if it's 17 on UNEA.
3. Updated with new routine functions

### CODE REVIEW

**Comment by IlseFerris** [comment]
Also forgive me if I did this wrong @theVKC, my GitHub for windows is broken :(

**Comment by theVKC** [comment]
You did OK. But... your 5181 is also on this branch. Can you delete the file from this branch only? I know that's hard without GitHub for Windows... did you get it running again?

**Comment by IlseFerris** [comment]
Nope, still the same error.  I will pull the 5181 off

**Comment by IlseFerris** [comment]
#donezo

Also GitHub is being a huge pain today.

**Comment by theVKC** [comment]
#Truth

**Pull request merged**
