### PR TITLE
adding AREP boxes to scripts

### PR DESCRIPTION
**Pull request by CDPotter**
Affected scripts
CAF
CAR
CC
EMER
GRH HRF
HRF
HCAPP
HC renewal
LTC 1503
LTC Renewal
Verifications needed.

Ran into issues with dialog editor and CSR. Will try to add checkbox
soon.

### CODE REVIEW

**Comment by CDPotter** [comment]
Kept getting a program crashing error when trying to edit the CSR dialog. I finished up the rest and will look into what's going on with the CSR

**Comment by theVKC** [comment]
Hmmm. Any ideas as to why this is happening?

**Comment by RobertFewins-Kalb** [comment]
Too many objects. I had the same problem when modifying the dialog for ADD STAT TO WORD.

**Comment by CDPotter** [comment]
When I do get it working should I tack it onto this pull request?

**Comment by CDPotter** [comment]
OK I've added the CSR, this is the versions of all the script that were currently determined to need this change. 
CAF
CAR
CSR
Client contact
EMER
GRH HRF
HRF
HCAPP
HC renewal
LTC 1503
LTC renewal
verifs requested

**Comment by theVKC** [comment]
Shoot. I have a merge conflict on this one. It'll require command line debugging and that's unlikely to happen today. I know you're out tomorrow @CDPotter so I'll try it and email you Monday if we run into issues...

**Comment by CDPotter** [comment]
Shoot indeed, was that because I updated a large number of files in one pull?

**Comment by theVKC** [comment]
No, I don’t think so. I think it might be because I made a change to one of the files, and it’s probably nothing.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Pull request merged**
