### PR TITLE
Resolved #1789: SNAP E & T student info update

### LINKED ISSUE #1789: SNAP E & T student info updates needed
Needs following information to be updated: 
* Eligible student needs to be student
* Directions to include sending a verification request form for E & T contact
* Informative message that a 30 day TIKL is automatically made when a manual referral is made.

### PR DESCRIPTION
**Pull request by IlseFerris**
Blip: "Additional instruction added for using the script to include sending a verification request form for E & T contact, informative message that a 30 day TIKL is automatically made when a manual referral is made. 'Eligible student' manual referral option was changed to 'student'.

### CODE REVIEW

**Comment by theVKC** [comment]
@IlseFerris: your pull request title doesn't match the new requirements. Please retitle it to match the new formatting. :)

**Comment by theVKC** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts#title

**Comment by IlseFerris** [comment]
Pull request and issue have been updated.

**Comment by theVKC** [comment]
@IlseFerris: you updated the issue and left the pull request under this title. Your issue title now doesn't make a lot of sense... :/

**Comment by theVKC** [comment]
@IlseFerris: issue's don't resolve pull requests....

image

**Comment by IlseFerris** [comment]
this should be good to go. Multitasking fail...wah wah!

**Pull request merged**
