### PR TITLE
Bulk addess report

### PR DESCRIPTION
**Pull request by CDPotter**
#567 's request

### CODE REVIEW

**Comment by theVKC** [comment]
@CDPotter, please rename file BULK - ADDRESS REPORT.vbs. Right now, it's missing the BULK.

**Comment by CDPotter** [comment]
Name has been fixed, sorry!

**Comment by theVKC** [comment]
Looks great! Can you write up instructions (if you haven't done so already, because you're pretty on top of things)?

**Comment by CDPotter** [comment]
For when we get this back up and running.

**Pull request merged**
