### PR TITLE
Resolves #1884, Mic drop dail scrubber update

### LINKED ISSUE #1884: DAIL send NOMI needs update for release for Mic Drop
A few enhancements are needed in preparation for Mic Drop's release on Monday. These include: 
* MEMO sending to AREP and SWKR if client has AREP and/or SWKR
* Navigation back to the DAIL once actions are completed
* Comments
* last day for recert variable to be adjusted by user if necessary

@theVKC, assign this to me. I've got this.

### PR DESCRIPTION
**Pull request by IlseFerris**
BLIP: The current script has been enhanced to send MEMOS to the recipient and SWKR/AREP if recipient has a SWKR/AREP who gets notices, navigate back to DAIL/DAIL when actions have been completed, and the option to fill in the last day of the recert period.

### CODE REVIEW

**Comment by theVKC** [comment]
I can't pull this until after the Monday release, @IlseFerris, as it's an enhancement and I don't want it going to the release branch.

**Comment by IlseFerris** [comment]
Since the last day for recert variable wasn't writing into the MEMO (it was just leaving it blank) I would argue that this is a bug. Anyway to pull it in now?

**Comment by theVKC** [comment]
Mic Drop won't be live in release Monday (only master), so I don't really want to pull this in to release Monday.

**Comment by IlseFerris** [comment]
Agreed, just needs to be in master

**Comment by theVKC** [comment]
Then I will wait until Monday. :/

**Pull request merged**
