### PR TITLE
ADDRESSES #710 Adding functionality for testing cases before the 16th. 

### PR DESCRIPTION
**Pull request by CDPotter**
BLIP: added a new function for developer mode to allow it to be run on CM+1 before the 16th like it used to.

### CODE REVIEW

**Comment by CDPotter** [comment]
Should this be resolves or addresses?

**Comment by IlseFerris** [comment]
Maybe just addresses.

**Comment by theVKC** [comment]
@IlseFerris and/or @C-Love, can you test this before we pull it in?

**Comment by IlseFerris** [comment]
I can test this tomorrow to confirm.

**Comment by IlseFerris** [comment]
Hey @CDPotter  I've been going over this REVS scrubber coding, and I have review determination coding that is solid that accounts for cases that don't have a review date for SNAP (never been open, and for cases that have a CASH review for this year and a SNAP review for next year). I tested it on your case load, and also a caseload heavy on GRH and other cash programs, and it's working at 100%.

Can you update your pull request to reflect the date changes only, and I will pull my code in once @vkc pulls yours in? Thank you!

**Comment by CDPotter** [comment]
Did you test it on cases where SNAP was open (not closed) but the revw panel still has the same renewal date as the current cash renewal? That is what I was solving.

**Comment by IlseFerris** [comment]
Yes, I incorporated it into the newest version that I built this morning :)
Honestly it's pretty similar to what you have, but I have the recert_status NO/YES in a larger If...else

**Comment by CDPotter** [comment]
Alright, rolled it back and only included the dev mode change. Changed name and description as well.

**Comment by IlseFerris** [comment]
@CDPotter Thank you, thank you, thank you!

**Comment by theVKC** [comment]
@IlseFerris, I'm "@theVKC" and not "@vkc". Don't know who that other person is.

**Comment by IlseFerris** [comment]
This is why I need to eat carbs.

**Comment by RobertFewins-Kalb** [comment]
This person...

https://github.com/VKC

...whose avatar looks like the Legion of Doom's headquarters...

**Comment by theVKC** [comment]
Per @IlseFerris I'm pulling this without direct review of the changes (it isn't live yet).

**Pull request merged**
