### PR TITLE
Resolved #2006: Housing Grant FIATer update.

### LINKED ISSUE #2006: Housing Grant FIATer update
Make the HAG FIATer able to only FIAT a single month OR multiple months.

I'll take it.

### PR DESCRIPTION
**Pull request by StormageddonDLOA**
Adds the ability to FIAT only one month or FIAT multiple months.

### CODE REVIEW

**Comment by theVKC** [comment]
@StormageddonDLOA: this is being tested and we're running into glitches. Just curious: how did you test this locally? If you ran it on fake (or real) cases, can you email me those cases?

**Comment by StormageddonDLOA** [comment]
I tested it on a fake case: 226571.

I ran it in 12/15 and just tested the single month FIAT as I wasn’t changing the rest of it. I was getting an issue with it not updating the prospective amount and had to change the position the script was putting in the “x” to select subsidy/tribal part in FIAT to a 17 from 18 but thought it must be due to being in the training region. I put it back to 18 for the final version as that is where it was originally and is also where it was in the part of the script that I didn’t change.

Hope this helps,
Tim

**Comment by StormageddonDLOA** [comment]
Or that’s possibly that I changed it to 18 from 17 on the position the script enters the “x” (I forget exactly). ☺

**Comment by theVKC** [comment]
@StormageddonDLOA: unfortunately we're still getting issues with this when we test it. I'm closing this pull request today. You have until tonight to pull it in in-time for inclusion in the March release. Otherwise we'll delay it until April.

**Pull request closed without merging**
