### PR TITLE
Removing x102 from script

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
...and adding multi-county handling

### CODE REVIEW

**Comment by theVKC** [comment]
@RobertFewins-Kalb, this goes in RELEASE, not BETA.

**Comment by RobertFewins-Kalb** [comment]
The problem code is in BETA though (worker_county_code = "x102")

**Comment by RobertFewins-Kalb** [comment]
I will submit a fix to RELEASE as well

**Comment by RobertFewins-Kalb** [comment]
Ah... BETA release. Sorry

**Pull request closed without merging**
