### PR TITLE
Resolves #2292 and Resolves #2336 -- Updates to INAC Scrubber

### LINKED ISSUE #2292: Enhancement/Input Needed >> INAC Scrubber mode for users without MMIS access
Anoka Co has users that will not be given MMIS access but will have a MAXIS caseload. As cases convert to METS, more caseloads are going to be MAXIS CASH & SNAP only. We would like a way to bypass MMIS for those users.

I am hoping there is a way to determine user permissions in REPT/USER (if you sort by Supervisor, it looks like it displays user permissions, but it doesn't make a whole lot of sense to me). I'm thinking MMIS Bypass Mode would also check for the programs that closed that months and ignore cases that closed on health care. That way, we could prevent users from running a version that has fewer checks in hopes of clearing more of their INAC cases.

We currently have an MMIS Bypass INAC Scrubber running locally, but I would rather not invite confusion with users.

What are peeps, thoughts?

### LINKED ISSUE #2336: Enhancement -- Add err_msg handling to INAC Scrubber
on it

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
BLIP: The INAC Scrubber can now be used to bypass MMIS should the user not have access. As a safeguard, it will not transfer cases that closed in the INAC month on health care to Closed Cases. Additionally, err_msg handling has been added for simpler data validation, and the dialog has been renamed Dialog1 for chainloading.

### CODE REVIEW

**Comment by theVKC** [comment]
Do you still have `MAGI_cases_closed_four_month_TIKL_no_XFER` handling in there? Users don't have that added to GlobVar (nor will they). I did a Ctrl-F on the file after encountering a bug and it doesn't look like it works unless that's set to True on GlobVar.

Can you remove references to `MAGI_cases_closed_four_month_TIKL_no_XFER` entirely? If you could also remove it from GlobVar in your pull, that'd be swell.

A good way to test it would be to remove the `MAGI_cases_closed_four_month_TIKL_no_XFER` reference from your agency's branch, then try running developer mode. That's what I did to bust it up.

**Comment by RobertFewins-Kalb** [comment]
I accidentally removed `IF MAGI_cases_closed_four_month_TIKL_no_XFER = "" THEN MAGI_cases_closed_four_month_TIKL_no_XFER = FALSE`

That allowed us to test four run scenarios...
* Agency hangs on to MAGI cases for 4 months after closing for no-or-incomplete renewal AND MMIS is running.
* Agency hangs on to MAGI cases for 4 months after closing for no-or-incomplete renewal AND MMIS is not running.
* Agency is not hanging on to MAGI cases for 4 months yadda yadda yadda and MMIS is running.
* Agency is not hanging on to MAGI cases for 4 months yadda yadda yadda and MMIS is not running.

**Comment by RobertFewins-Kalb** [comment]
I would be happy to plop that line back in.

**Comment by theVKC** [comment]
Actually, I'm thinking the opposite. I want it removed. I think all agencies should hang on for 4 months now. The info has been out there for counties to act on for months.

The issue was that I still saw the logic in there. I'm thinking that variable should be stricken from the record, right?

**Comment by RobertFewins-Kalb** [comment]
In that case, we can rework the logic to create two run modes...
* MMIS Run mode: normal run mode that checks for active HC in MMIS. If the case closed in the INAC month for no-or-incomplete renewal, the script does not transfer the case and TIKLs for 4 months to XFER to Closed Cases if no progs are open.
* MMIS Bypass mode: w/ regards to HC, checks for HC that closed this month for _any_ reason and keeps those cases in the caseload, asking user to double check case to determine if it needs to be hung on-to...does not TIKL for 4 months hanging-on-to (sic)

**Comment by theVKC** [comment]
I like it, as long as we don't end up on two paths that consist of two mostly identical large code blocks, as it previously existed.

**Comment by RobertFewins-Kalb** [comment]
That would not be the case. @CDPotter and I will work on this today and just modify the pull request that's sitting out there...which is just one script run through

**Comment by theVKC** [comment]
Good deal! Thank you both!

**Comment by RobertFewins-Kalb** [comment]
Give it a looky loo. Should be good to go now. We can update the wiki. Please let HC policy not change for a while. This thing is a beast.

**Comment by theVKC** [comment]
Nice job. And yes, let's hope for few changes.

**Pull request merged**
