### PR TITLE
NOTES - MFIP SANCTION CURED.vbs

### PR DESCRIPTION
**Pull request by khiestand**
This is a case note script for a financial worker to note the details of a MFIP sanction being cured.

### CODE REVIEW

**Comment by IlseFerris** [comment]
Awesome Kelly, this looks great!  Just as an FYI there is another function called  "start_a_blank_CASE_NOTE", and it includes you PF9.
And yes, I am spying from afar since I couldn't be there with you all today...sadness.

**Comment by khiestand** [comment]
Thanks!  There were a few new functions that I was not aware of since last writing scripts!  We missed you today for sure!!

**Comment by theVKC** [comment]
This resolves #772.

**Comment by IlseFerris** [comment]
Awwww!  Thanks Kelly, I sure missed you all too!  I will be getting out some documentation about for scriptwriters about the master functions really soon.  Like I need to have it ready for next week, so keep an eye out for it :

**Pull request merged**
