### PR TITLE
Adding comments to BULK-DAIL REPORT.vbs

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
I guess I just busted this out without considering that other people would want to know how it works. Sorry, gang.

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
In response to issue #1335

**Comment by IlseFerris** [comment]
Awesome, thank you!  All is forgiven :)

**Comment by RobertFewins-Kalb** [comment]
Let me know if it needs additional comments

**Comment by theVKC** [comment]
@RobertFewins-Kalb, why'd you set the obj.excel to be not visible?

**Comment by RobertFewins-Kalb** [comment]
I am not sure. I think I was going for effect when the report becomes visible at the end. I'll go ahead and change that...

**Comment by RobertFewins-Kalb** [comment]
It is set to True. I think originally I was playing with the idea of setting it to False so that it would run invisibly and then pop up with the results. I deleted the extra objExcel.Visible = True because it was not needed.

**Pull request merged**
