### PR TITLE
Create new notes main menu

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
Creating consolidated NOTES main menu with alpha-split tabs

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
Closes #799

**Comment by theVKC** [comment]
Say, @RobertFewins-Kalb...

...could I ask you to also modify the existing NOTES - MAIN MENU scripts to contain a simple redirect to this script?

**Comment by RobertFewins-Kalb** [comment]
Yes. Sorry aboot that.

**Comment by RobertFewins-Kalb** [comment]
I am going to create a new REDIRECT NOTES. Should I also modify the existing NOTES redirects to point at the new REDIRECT?

**Comment by RobertFewins-Kalb** [comment]
Done

**Comment by theVKC** [comment]
Nice work. We'll test it tomorrow and see how it goes.

**Pull request merged**
