### PR TITLE
Update MEMOS - DUPLICATE ASSISTANCE WCOM.vbs

### PR DESCRIPTION
**Pull request by C-Love**
Script will now add a WCOM to an MFIP notice as well - when client on case has received SNAP on another case.

### CODE REVIEW

**Comment by C-Love** [comment]
Issue #1263

**Comment by theVKC** [comment]
Hey @C-Love, just noticed this: in the WCOM when it adds the notice, you're using `else if` instead of `elseif`. I have a couple of concerns about that:

1. `Else if` is somewhat poor syntax in VBscript, it behaves different than `elseif` from my experience (https://msdn.microsoft.com/en-us/library/5h27x7e9(v=vs.84).aspx)
2.  Is it either an MFIP notice or a SNAP notice? i.e., can't be both at once? If it can be both simultaneously, it should be separate IF...THEN statements, not IF...ELSEIF statements. Make sense?

**Comment by theVKC** [comment]
@C-Love, I'm closing this pull request just to keep things clean. Please repull when you get the above resolved (if you did that already, thank you). :)

**Comment by C-Love** [comment]
Thank you. Sounds good - I think I have it done - just needs a bit more testing.

**Comment by theVKC** [comment]
Good deal! Enhancement freeze ends Monday, at which point feel free to resubmit. :)

**Pull request closed without merging**
