### PR TITLE
Update NOTES - MEDICAL OPINION FORM RECEIVED.vbs

### PR DESCRIPTION
**Pull request by Farleight**
Removing diagnosis language from Script due to HIPAA concerns. Text added to dialog, reminding workers not to enter diagnosis info in case note. Tab order reassigned to fix checkbox being out of place. One typo fixed in explanatory comment, because it bothered me.

### CODE REVIEW

**Comment by theVKC** [comment]
Looks good! One thing: could we cite the PQ (something like "per PQ #16506") in the dialog?

Also FYI: we typically tag the issue we resolve in the title of the pull request. So, you could properly title your pull request "Resolves #1667: update NOTES - MEDICAL OPINION FORM RECEIVED.vbs"...

**Comment by theVKC** [comment]
(citing PQ because you know someone somewhere is going to want to know why they can't)

**Comment by Farleight** [comment]
No problem. Is there a special way to edit an existing pull, or do I re-pull?

**Comment by theVKC** [comment]
Easy.

1. Navigate to your fork (github.com/<your user name>/DHS-MAXIS-Scripts)
2. Switch to the branch you created when you started your pull request (yours is "patch-4")
3. Navigate to the file you want to change
4. Edit the file, then re-commit

The pull request should automatically adjust to reflect the new changes in your branch. :)

**Comment by Farleight** [comment]
Yeah, you lost me at Patch 4. I'm on the Main Branch, but nothing under the dropdown looks promising. How do I switch to Patch 4? I can access my Files Changed, which has an edit button, but it seems to be for comments.

**Comment by theVKC** [comment]
Does this help?

image

**Comment by Farleight** [comment]
Yeah, that's where I am... but there is nothing that expressly states Patch 4.

**Pull request merged**
