### PR TITLE
Create NOTES - MFIP TO SNAP TRANSITION.VBS

### LINKED ISSUE #773: MFIP transitioning to SNAP case note
Hennepin county family worker suggested this. Is this an area that is error prone/used enough to warrant this?  Thanks team!

### PR DESCRIPTION
**Pull request by courtrightd**
Resolves #773

### CODE REVIEW

**Comment by theVKC** [comment]
Hey @courtrightd: can you update the MAIN MENU script for this? It's the difference in this being included in this release or next... :)

**Comment by courtrightd** [comment]
I am actually working on the main menu expansion to add this today!  I will try and have a pull request sometime this afternoon, just have one weird bug to sort out.

**Comment by theVKC** [comment]
Awesome. Can you include that in this branch you made? That way, it's just one pull request I have to approve (easier tracking).

**Comment by courtrightd** [comment]
Menu has been updated, added a couple final tweaks to the script that were suggested to me today.
This is now ready to be pulled when you are @theVKC

**Comment by theVKC** [comment]
Eeeek! One problem @courtrightd, the extension on the file is all caps. Can you fix that real quick?

**Comment by courtrightd** [comment]
Should be good.

**Pull request merged**
