### PR TITLE
Created support for foldering on AGENCY CUSTOM

### PR DESCRIPTION
**Pull request by lpshanley**
Created the ability for the AGENCY CUSTOM script to locate folders. It can also navigate through the folders and detect other scripts and folders in those sub folders! Enjoy :smile:

### CODE REVIEW

**Comment by lpshanley** [comment]
Enjoy :-)

**Comment by lpshanley** [comment]
Don't pull this yet

**Comment by lpshanley** [comment]
I need to finish the case notes...

**Comment by lpshanley** [comment]
And it needs the change i made to the functions lib changed first! :-)

**Comment by lpshanley** [comment]
This should be everything. You are free to merge whenever. Let me know if their are any issues.

**Comment by theVKC** [comment]
Sorry @lpshanley, I'm going to have to close this pull request. You did your work for both issues on your master branch, which makes it impossible for me to regress the two separate issues (the new function and the new agency customized script). When you work on an issue, please create a branch for it, then pull that issue in. The "Scriptwriter Collaboration" document in SIR should lay out the process.

In any case, I also see it as problematic that it's a separate function that has to be added each time you case note. We should have this functionality included by default in the existing write_variable_to_case_note functions, not really as a separate function. More functions = more confusion for newer scriptwriters. If you can make those changes, resubmit your requests and I'll look it over again. Thank you!

**Comment by lpshanley** [comment]
You wrap the variable that contains the input in the function. There is no other good way to do it... this is how every script language I’m aware of functions with escape strings... I’ll look at it again over lunch.

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Comment by theVKC** [comment]
What I’m looking for is working that functionality into the existing function, instead of creating a new one…


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by lpshanley** [comment]
Wait are you referring to not having it in the case note scripts and only having it on a functional level? Are you ok with having a function that will clean user input still and just applying that function to the case note function so it’s not in the actual NOTE script? If that’s the case we agree about 1000 percent

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Pull request closed without merging**
