### PR TITLE
Resolves #183

### PR DESCRIPTION
**Pull request by IlseFerris**
BLIP: New script which is a template for explaining how income is budgeted on a case.

### CODE REVIEW

**Comment by theVKC** [comment]
Your pull request is causing a merge conflict because your main menu needs to be updated. @MelissaFox-Stearns just pulled some work in.

**Comment by theVKC** [comment]
Any ETA on fixing this, @IlseFerris? :)

**Comment by IlseFerris** [comment]
I'll update it this morning

**Comment by theVKC** [comment]
Thank you!

**Comment by IlseFerris** [comment]
I'll pull the two files in separately. Standby for the pulling.

**Pull request closed without merging**
