### PR TITLE
Create ACTIONS - HOUSING GRANT FIATER

### PR DESCRIPTION
**Pull request by StormageddonDLOA**
This new script will do the FIATing for the worker when a MFIP case is receiving a subsidy but is still eligible for the Housing Grant. Finishes issue #1318.

### CODE REVIEW

**Comment by theVKC** [comment]
@StormageddonDLOA: closing this issue, not because I don’t love the script, but due to a few nitpicky issues with it. :)
1. The .vbs is missing from the file itself (rename the file).
2. `name_of_script` needs all characters with caps, except for the file extension
3. We have a function for case number finder, and I think I'd like to use it here. In fact, I think you helped with that one. :)
4. Could you add another loop around the main dialog containing our new check_for_password function? See CAF for an example (or ask @MelissaFox-Stearns)
5. When you go to FIAT, you need to go to `("FIAT", "____")`. This clears out any residual data in the command line which may be left over due to MAXIS being weird (it's good error proofing).
6. Needs a `script_end_procedure("")` at the end, for statistics (@GayS would be pleased to include this)
7. I'll need you to add a button to the ACTIONS - MAIN MENU script for this. :)

Otherwise, I love the content. It looks solid to me. The only other issue is we're in an enhancement freeze until Monday so we can test the new enhancements elsewhere (see SIR scripts calendar). So, please pull this again Monday with the changes if you can. :)

**Comment by StormageddonDLOA** [comment]
I’m out next week so I’ll do the pull request the week after.

**Comment by theVKC** [comment]
That should be fine, @StormageddonDLOA. If you can get it in early Monday, I can easily incorporate it into the next beta.

**Comment by StormageddonDLOA** [comment]
I am having an issue where my dialog editor won’t let me make any dimension an odd number.

i.e. if I try to make a text box 60, 55, 215, 10 the editor will change it to 60, 54, 216, 10

**Comment by theVKC** [comment]
This could be that version difference. You could always just find/replace that.

**Pull request closed without merging**
