### PR TITLE
Resolve #2031

### LINKED ISSUE #2031: NOTES - GOOD CAUSE RESULTS: name_of_script needs to be in caps
@GayS, do you want this one? It's tagged for April because it's not critical enough to break freeze.

### PR DESCRIPTION
**Pull request by GayS**
changed script name to upper case for stat gathering

### CODE REVIEW

**Comment by GayS** [comment]
Updated the ACTION scripts to move stat collection block to follow start timer at beginning of scripts part of #2042

**Comment by theVKC** [comment]
@GayS: something here is causing a merge conflict...

Can you pull your Good Cause stuff from a separate branch (then create a new pull request for it), then try syncing your master repo again?

**Comment by GayS** [comment]
sorry - I have no idea how to fix this.

**Comment by theVKC** [comment]
Can you pull request your master branch from my master?

**Comment by theVKC** [comment]
[Scriptwriting Training.docx](https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/files/215992/Scriptwriting.Training.docx)

Pages 17-18 should show the proper Pull Request process. If you can send your Good Cause script through that, that'd be great.

Basically, you're doing all the work in your master branch, and that's caused this issue. I'll close this pull request, but you can still get the work done by syncing your master branch with mine. But, it'd help if the Good Cause stuff was in a separate pull request.

**Pull request closed without merging**
