### PR TITLE
MFIP REI fix

### PR DESCRIPTION
**Pull request by CDPotter**
MFIP REI area has changed since coded. reworked it to just REI everything by send keying as many Ys as needed. (how snap works currently)

### CODE REVIEW

**Comment by CDPotter** [comment]
@theVKC How do I add an excel file to the repository?

**Comment by theVKC** [comment]
@CDPotter with GitHub desktop. :P

**Comment by theVKC** [comment]
@CDPotter: did you mean to remove the Excel file entirely?

**Comment by CDPotter** [comment]
The plan was the remove it then add the new one since I didn't find an edit option on github browser. I can't seem to figure out how to roll that commit back. Can you merge and then I will try to use github for windows again (been so long) to put the new template up?

**Comment by theVKC** [comment]
I don't want to lose it. I'd rather have you use GitHub Desktop and just re-submit (you can now do the entire thing from desktop and it's very slick.

http://stackoverflow.com/questions/1783405/checkout-remote-git-branch

**Comment by CDPotter** [comment]
I've got a copy waiting on my desktop to upload but that's alright. I'll give it a shot.

**Comment by theVKC** [comment]
I'll close this one then. Let me know if you have questions!

**Pull request closed without merging**
