### PR TITLE
Resolves #657 New Script - Update EOMC List

### LINKED ISSUE #657: EOMC enhancement or variation ~ Compare initial EOMC data to actual closed cases on or after 1st of the month
We use the EOMC script for our HC and cash auto-close cases to help prevent the cases tied to a SWKR from closing. We want to be able to run a report  on or after the first of the month to determine what cases of those above mentioned, if any, actually closed. I know there is INAC, but that doesn't verify program(s). Copy of our latest EOMC spreadsheet was emailed to Veronica via SIR mail, per her suggestion.

### PR DESCRIPTION
**Pull request by courtrightd**
BLIP: This script will check all cases on a saved REPT/EOMC excel file from a previous month and update the file with current status for each program.

### CODE REVIEW

**Comment by theVKC** [comment]
@courtrightd: can you update the instructions Wiki for this between now and release?

**Comment by courtrightd** [comment]
No, as the time of update was prior to the current time so I cannot make your statement true.

**Comment by theVKC** [comment]
In other words, you already built it? :P

Also, can I get some folks using other versions of BlueZone to test this?

- @IlseFerris (v5.1c2 and something older)
- @C-Love (v6+)
- @MelissaFox-Stearns / @StormageddonDLOA  (v6+)
- @CDPotter / @RobertFewins-Kalb (v5.1c2)

If this works across versions, that BrowseForFile should earn you a metal.

**Comment by courtrightd** [comment]
To clarify: All credit for BrowseForFile goes to Robert and/or Charles, it was stolen directly.

**Comment by theVKC** [comment]
Well then they should get the metal too. I wonder if the state will give me a 3d printer.

**Comment by RobertFewins-Kalb** [comment]
All glory to the Google

**Comment by theVKC** [comment]
#AGttG

**Pull request merged**
