### PR TITLE
Fix to ACTIONS - TRANSFER CASE

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
I failed to reinsert logic that automatically determine County of Financial Responsibility change date...

### CODE REVIEW

**Comment by theVKC** [comment]
#DontUseTheMasterBranchForYourFixes :P

**Comment by RobertFewins-Kalb** [comment]
#oops
Also, the BETA repo does not have the updates.

**Comment by theVKC** [comment]
Oh, I know! We’re not ready for beta release. If you want to pull it into beta directly as a bug fix:


1.       Fork the beta repo

2.       Create a new branch from the beta repo

3.       Copy the file that changed from your master branch into the new repo

4.       Pull request your new branch into the main beta branch

Otherwise, it’ll have to wait until next week when I do the next beta release.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by RobertFewins-Kalb** [comment]
On it.

**Pull request merged**
