### PR TITLE
Update NOTES - CHANGE REPORT FORM RECEIVED.vbs

### PR DESCRIPTION
**Pull request by MelissaFox-Stearns**
@TheVKC, @IlseFerris
What do you guys think of this? 
This script changes the file from Change Report Form Received to Change Reported. Comes included with combo box to choose how the change was reported (CRF, Phone contact, Email, Etc). The header of the case note will show what type of change was reported based on what fields the worker entered. Also added was a checkbox next to each field to case note if we have verification for the change.

### CODE REVIEW

**Comment by theVKC** [comment]
I like it, but... we should talk details (nothing major, just ideas I have for you). We could arrange a phone call tomorrow? I'm also trying to work out a Stearns site visit.

**Comment by MelissaFox-Stearns** [comment]
Yes please!. I'm totally up for ideas,  I love ideas!  I'm on interviewing this week so I am like figuratively running around with my head cut off all day, its nuts. Hows about 4:00 ish? Also we can chat after work on my cell of course ...unless I need to be at my computer.

**Comment by theVKC** [comment]
Hey @MelissaFox-Stearns, do you want me to close this one so you can work on the ideas as we discussed on Wednesday?

**Comment by theVKC** [comment]
BTW, this was tied to issue #1036.

**Comment by MelissaFox-Stearns** [comment]
Yes! This will be bigger and better.  :)

**Pull request closed without merging**
