### PR TITLE
NOTES - CLIENT CONTACT

### PR DESCRIPTION
**Pull request by GayS**
Consolidated client contact & call center contact into one dialog box, removing redundant fields, inserted auto date/time, used updated functions and option explicit.  Tested script with all to/from and contact_type options.

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
Request: could the dialog be modified to tighten everything up? It looks like the changes to the dialog are the call center checkboxes, and there is room for those in the existing FAS cl contact under the AREP checkbox for those checkboxes.

**Comment by GayS** [comment]
I can tighten the fields up – but not sure what/where you are asking to put the call center checkboxes??    Sorry – non-FW here. :}  Do people care if I re-arrange the fields?  I was trying to not change too much from the current script. But I would move the case number, date/time to the first fields – case note can stay in the same order.  Thoughts?

**Comment by theVKC** [comment]
OK, where did we land on this? @GayS or @RobertFewins-Kalb, has any more work been done on it? Admittedly I haven't had time for testing, but will ASAP.

**Comment by RobertFewins-Kalb** [comment]
Sorry...I was caught up in a few other things.

Here was my thought...
image


The AREP forms checkbox is back in. 
The overall format doesn't change for financial workers.
The editboxes and checkboxes are more tightly organized so the dialog only has to expand a little bit.

**Comment by RobertFewins-Kalb** [comment]
For a comparison...

The current client contact (height = 280)...
image


The proposed client contact change (height = 355)...
image


The modification above (height = 300)...
image

**Comment by GayS** [comment]
Great – thanks.


.

**Comment by IlseFerris** [comment]
Is there a way you could throw a 'follow up' button on this dialog?  Hennepin Co has an agency custom 'follow up' button they use.  It would be super helpful to have it on here.  Managers use the information from the stats of the usage of the follow up button to determine how much time workers need to continue to work on a case once they are done meeting with the client.

**Comment by RobertFewins-Kalb** [comment]
I can make the updates if the pull request is accepted. Thank you for taking the lead on this, Gay!

**Comment by GayS** [comment]
Collaboration is a good thing – thanks for your help!

**Comment by theVKC** [comment]
@RobertFewins-Kalb, are you waiting on me to pull this in? Can you side-pull (from @GayS to you in a new branch, then you make a pull request)?

**Comment by RobertFewins-Kalb** [comment]
If I submit a pull request, will Gay still get credit for her work too?

**Comment by RobertFewins-Kalb** [comment]
I don't want to be the god of thunder stealing

**Comment by GayS** [comment]
It took me a minute, but I did get it!  I should be able to spend some time this morning to make the changes  graciously suggested by Robert. ☺

Ps.  Collaboration is a good thing!

**Comment by GayS** [comment]
Collaboration is a good thing!  Let me know if there is any I need to do.

**Comment by theVKC** [comment]
@GayS is listed as a contributor on your version of the file. I think you're clear for pull request, @RobertFewins-Kalb. I'll close this pull request and await the next one.

**Comment by lpshanley** [comment]
Percy Jackson was a demigod not a god ☺

#SpidermanDerail

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Pull request closed without merging**
