### PR TITLE
Footer month not pulling into dialog (BETA & MASTER BRANCHES only)

### PR DESCRIPTION
**Pull request by IlseFerris**
This is only effecting the BETA and MASTER branches as this was a Doubtfire update. Also removed extra blank spaces.

### CODE REVIEW

**Comment by theVKC** [comment]
@IlseFerris, two things:

1. Is there an issue for this? (If not can you make one please)?
2. I don't see a second pull request for BETA. Can you do that for me?

Thanks dear!

**Comment by IlseFerris** [comment]
I didn't create an issue since it's Doubtfire related.  I can if you want one.  Also pulling to BETA now.

**Comment by theVKC** [comment]
Please do: because we closed the Doubtfire issue, we should reopen or create a new one. I use the issues to track, in order to create release notes, especially right now since someone changed 140-odd scripts this month. :P

**Comment by IlseFerris** [comment]
Resolves issue #1133

**Pull request merged**
