### PR TITLE
RESOLVES #1889 #1899 Updating BULK and NOTICES with new dynamic DLG style

### LINKED ISSUE #1889: Update NOTICES and BULK menus to follow new NOTES conventions
The new NOTES MAIN MENU conventions are less error prone than the current dynamic dialogs in NOTICES and BULK. They should be updated to all be the same convention.

### PR DESCRIPTION
**Pull request by CDPotter**
BLIP: BULK and NOTICES are in the same menu style as NOTES (in master)

Tested all buttons on both scripts.

### CODE REVIEW

**Comment by theVKC** [comment]
I like the way this looks! I have to check it against the function I'm working on but it should be good.

**Comment by theVKC** [comment]
@IlseFerris: can you evaluate this for Hennepin's blocking of NOMI and Appointment Letter? I assume @CDPotter did not include that functionality. If it needs it, let me know and we can create a new issue.

**Comment by IlseFerris** [comment]
NOMI is available to users. Appointment letter is not.

**Comment by theVKC** [comment]
If you can check the new version I just pulled in, that'd be great @IlseFerris!

**Comment by CDPotter** [comment]
I totally spaced, sorry!

**Comment by IlseFerris** [comment]
No worries, you're not expected to know all of x127's quirks. Testing in a moment, standby.

**Comment by theVKC** [comment]
@IlseFerris: I'd imagine you could add something to the FOR...NEXT... something like `IF ButtonPressed = appointment_letter AND county = "x127" THEN...`

**Comment by CDPotter** [comment]
Wouldn't it be easier to add a line in APPT letter for a script end procedure if X127 is county code?

**Comment by theVKC** [comment]
...or that.

**Comment by CDPotter** [comment]
I'd be hesitant to add county specific things to the main menus since we're trying to simplify them. Just my two cents though.

**Comment by IlseFerris** [comment]
I can add it into the appt letter script itself. Seems like the right move.

**Comment by theVKC** [comment]
Great. If you can throw a new issue on there, that'd be great!

**Pull request merged**
