### PR TITLE
Updated to include dup assistance WCOM

### PR DESCRIPTION
**Pull request by CDPotter**

### CODE REVIEW

**Comment by theVKC** [comment]
Looks good, but very minor tweak: can you add "NEW 07/2015!!!" to the text field please? Need to call attention to that fine work you did. :)

**Comment by CDPotter** [comment]
No problem, it has been added.

**Comment by theVKC** [comment]
So close! This says "NEWS" instead of "NEW"...

**Comment by CDPotter** [comment]
Whoops, COLA day my brains a bit fried.

**Pull request merged**
