### PR TITLE
Issue #2906 - BULK Case Transfer

### PR DESCRIPTION
**Pull request by C-Love**
Add enhancement to allow search to filter by recently closed programs  (note I have changed my tab settings so much of the changes indicated in the diff are due to that change in atom)

### CODE REVIEW

**Comment by theVKC** [comment]
The diff is very large... was this tested? I don't have bulk cases to transfer for testing purposes...

**Comment by C-Love** [comment]
Yes, this is actually code that has been running locally for many months in Ramsey County. I did test this when I saved it this time. I basically just copied a file that has been working. I believe a part of the reason the diff is SO large is that it is comparing white space changes and I have a package in atom that changes all my tabs to spaces so there were lots of those changed.

**Comment by theVKC** [comment]
Please test it in master and let me know if it's working as expected!

**Comment by theVKC** [comment]
Wait, what issue is this tied to?

**Comment by C-Love** [comment]
Switched the pull request name because I typed poorly

**Comment by C-Love** [comment]
Issue #2609

**Comment by theVKC** [comment]
Thank you! I updated the project board to reflect this is in testing. Please confirm once it's working as expected!

**Pull request merged**
