### PR TITLE
Create new file

### PR DESCRIPTION
**Pull request by ramonalisa1**
This script will review a caseload for guardianship fee, pull data in spreadsheet, and delete rows from the spreadsheet for those who have no fee.

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
Where is "guardianship fee" found in MAXIS?

**Comment by RobertFewins-Kalb** [comment]
Nevermind...STAT/PDED

Easy Peasy, Lemonsqueezy. I can have a modification ready in a few minutes.

**Comment by theVKC** [comment]
OK @ramonalisa1 and @RobertFewins-Kalb, I'm super sorry I didn't get to this in a timely fashion. I've been somewhat busy with new job duties, and a bit of time off. I've just tested this and I have two questions:

1. I'm getting a weird "* * * * " on the first case I run with this. Is that normal? Hard time getting to PDED perhaps? I'm testing it on Robert's fake cases if that helps.
2. It's making a blank record in the Excel spreadsheet at the end of each worker to run. Not a big deal if you're running a single worker, but yes a big deal if you're running multiple, as it stops when it sees that blank record. Can we include some handling for this?

Because I'm under some pressure to put beta release out tonight, I'm going to close this request for now. But, Lisa, if you (or Robert) can get the above addressed, go ahead and pull it and I'll fast track it into beta in the next week or so. No worries.

**Comment by ramonalisa1** [comment]
@RobertFewins-Kalb I am not sure I can figure this out.  Any thoughts?

**Comment by RobertFewins-Kalb** [comment]
Sorry, folks. I was on the road when all this was going down. I can take a quick look.

**Comment by RobertFewins-Kalb** [comment]
No I can't. The training region is not available.

**Comment by RobertFewins-Kalb** [comment]
WAIT, @theVKC!!! Carl is broken. Case 211858 has been stuck in background for a month. That might be the first case is only dumping "* * * * " because the screen isn't moving off SELF!!

**Comment by RobertFewins-Kalb** [comment]
@ramonalisa1, the script looks like it should work just fine. It's not you, it's me :)

**Comment by ramonalisa1** [comment]
Thanks @RobertFewins-Kalb and @theVKC .  That baffled me as it seemed to work fine when I tested it.  One thing, I would like the script to format the amounts listed on the spreadsheet to dollars and cents.  How would I write that.

This is a good script.  We were finding that in our county, we had clients where the county appointed a guardian and county was paying the guardianship fees out of county dollars.  Many of these clients had been given a guardianship fee deduction to pay to their guardian, but the guardian was not taking the deduction.  Therefore, the county was losing some county dollars.  After comparing the spreadsheet, we found several where that was happening so not only is the script great, it is saving county dollars.  I would like to print the spreadsheet now once per month to give to our fiscal department to compare with guardianship bills it receives.  If this is something occuring in other counties as well, this may be a valuable one.  

The only issue is that in our small county, many of our clients are serviced by other counties so their case is not in our county number.  But we can come up with some sort of plan with fiscal to watch that.  In a large county, this could save lots of tax dollars!!

If you have any ideas on that, let me know...

**Pull request closed without merging**
