### PR TITLE
NOTES - INCARCERATION.vbs

### PR DESCRIPTION
**Pull request by khiestand**
This is a new case noting template script that Financial workers can use to note the details of a client incarceration reported to the agency.  It will note the HH member that was incarcerated, the incarceration start date, the incarceration location, the anticipated release date if known, the facility type, how the info was received, probation officer info if known, actions taken, other notes/comments, if STAT/FACI was updated, and if a TIKL was created to check for a release date.  The script will check to see if the HH member already has 5 FACI panels and notify the Financial Worker to clean them up before proceeding.  The script has the ability to update the STAT/FACI panel for the HH member incarcerated, completing the Facility name, Facility type, FS Eligible with an N, Date In, Date Out if applicable.

The documentation for this script has already been entered on SIR in the Script Wiki.

This script resolves issue #987

### CODE REVIEW

**Comment by theVKC** [comment]
@khiestand, the script looks good. Any chance you can add it to the MAIN MENU itself? I forget if @RobertFewins-Kalb published documentation explaining how to do that. If you aren't feeling confident, let me know and I'll do it between now and Monday when it gets released.

**Comment by RobertFewins-Kalb** [comment]
I have not

**Comment by theVKC** [comment]
#NotIt :P

**Comment by khiestand** [comment]
I don't think I can add the button?!  If I had documentation I totally would though :-)

**Comment by theVKC** [comment]
@RobertFewins-Kalb is plugging away at the documentation. If it's ready by Monday, would you be available to give it a shot then? Otherwise, I'll pull this myself and add it myself.

**Comment by khiestand** [comment]
@theVKC @RobertFewins-Kalb - I am actually going to be at the MFSRC Conference in St Cloud 10/5-10/7, so the earliest I would be able to touch this would be on Thurs 10/8.

**Comment by IlseFerris** [comment]
I can add the button since I am working on the NOTES main menu today.  @khiestand I'll just steal what you said on the SIR instructions "Incarceration - A case note template to note details of an incarceration and also updates STAT/FACI if necessary. "

**Comment by khiestand** [comment]
Thanks @IlseFerris!  You rock!! :-)

**Comment by theVKC** [comment]
Thanks @IlseFerris! If you can message me and let me know when it's pulled, I'll do both of these simultaneously.

**Pull request merged**
