### PR TITLE
Create new file

### PR DESCRIPTION
**Pull request by ramonalisa1**

### CODE REVIEW

**Comment by ramonalisa1** [comment]
@theVKC and @RobertFewins-Kalb .. On this one, it works.  However I would like it to delete the blank lines in the spreadsheet if none of them have a value.  Also, it is puting in _____ in the spreadsheet in some fields.  Any ideas?

**Comment by RobertFewins-Kalb** [comment]
@ramonalisa1 , I tried to fork your repo and then pull request into it, but it is too messy. Here's the file (copy/paste)...

https://raw.githubusercontent.com/RobertFewins-Kalb/DHS-MAXIS-Scripts/Patch-7/Script%20Files/Create%20new%20file.vbs

**Comment by theVKC** [comment]
@RobertFewins-Kalb, did you fork her entire repo or just the one patch branch?

**Comment by theVKC** [comment]
Looks like this is superseded by the next request. Closing because of that!

**Pull request closed without merging**
