### PR TITLE
Dialog ID error suppression

### PR DESCRIPTION
**Pull request by lpshanley**
This will suppress out of range error for now so that the result of the issue will be visible so it may be fixed. Please merge this.

### CODE REVIEW

**Comment by lpshanley** [comment]
Hey V. Please merge this so the I can debug the issue :-)

**Comment by theVKC** [comment]
We usually don't merge things like this into the main branch. Are you unable to "redirect the redirect" file to your repository? That's how I usually test changes before I deploy them...

**Comment by theVKC** [comment]
Basically, replace the URL in the redirect file with your repo, and then you can test it in your fork before it goes everywhere else...

**Comment by theVKC** [comment]
I'll merge it anyway since it's a simple enough fix, but I'd try that redirect trick if possible. :)

**Comment by lpshanley** [comment]
Thank you! We are also testing the redirect on Dave’s machine ☺

-Luke
“Valar dohaeris”
#DecimateTheErrorRate

**Pull request merged**
