### PR TITLE
Cola Auto Approved

### PR DESCRIPTION
**Pull request by RoyStearns**
Script will navigate to GRH/MSA/FS "Auto approved COLA" DAIL messages, copy them into case notes, delete the DAIL and create a report of all COLA messages.

Sorry I thought you wanted this in BETA.

### CODE REVIEW

**Comment by theVKC** [comment]
I'm holding on approving this one until I can talk to a policy expert about it. Hang tight. Just want to get some buy-in before making it official.

**Comment by theVKC** [comment]
I think I'm going to pull this right now, and wait for policy in a bit. I'll grab it and move it to a new folder. That way @RoyStearns gets the credit and we can sit tight on the deployment (good since it's not COLA time anyway). We need a good project name code-word for this script though (for the folder to be named). Any suggestions out there? I know @RobertFewins-Kalb, @courtrightd, and @IlseFerris love coming up with the code words...

**Comment by IlseFerris** [comment]
Operation Pepsi (since it's for the COLA).  Operation Coke didn't sound as cool.  Wah wah...

**Comment by RobertFewins-Kalb** [comment]
Operation Royal Crown

**Comment by IlseFerris** [comment]
And awesome work on that one @RoyStearns!  As a former LTC worker, I really appreciate any tools that help with those crazy times of the year!

**Comment by IlseFerris** [comment]
Hey @RoyStearns, do you have instructions written out for this script?  I would LOVE to see some if that's the case.

**Pull request merged**
