### PR TITLE
resolves #2966

### LINKED ISSUE #2966: QUESTION: Scripts updated to work with the modified new hire messages?
I'm not sure how or who to even submit this question to since this repository probably isn't being actively monitored. One of my workers has a question so I thought I'd put it on here just in case someone sees it :) She is wondering if scripts will be updated to work with the modified new hire messages? If someone sees this and is able to respond, great. If not, it's a-ok.

### PR DESCRIPTION
**Pull request by StormageddonDLOA**
Tweaks the DAIL scrubber to work on the NDNH hire matches.

### CODE REVIEW

**Comment by theVKC** [comment]
@C-Love: I have requested that you review this as you did the last one! :)

**Comment by C-Love** [comment]
@StormageddonDLOA - do you have time to pull the other script changes in ASAP? If not, I can pull the changes in that we have to the actual script file... We'd like to get these in so we can finish testing and approve

**Comment by C-Love** [comment]
@theVKC  - please pull this in - it does not resolve the issue but @IlseFerris will pull in a separate pull to resolve the rest of the issue

**Comment by IlseFerris** [comment]
I  just submitted the final part of this.

**Comment by C-Love** [comment]
Confirmed in Master that this change is correct and is working.

**Pull request merged**
