### PR TITLE
Many updates to NOTES - SHELTER FORM RECEIVED

### LINKED ISSUE #1207: Update NOTES - SHELTER FORM RECEIVED to be an actions script with additional handling
For the sake of ME reviewers, NOTES - SHELTER FORM RECEIVED should be case noting the date that the SF was received by the agency.

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
BLIP: This update requests additional shelter expense information related to the document received. It also gives the user the opportunity to update MAXIS while also case noting what is being updated.

Resolves #1207

### CODE REVIEW

**Comment by theVKC** [comment]
@RobertFewins-Kalb, has this become an actions script? If so, should it be moved?

**Comment by RobertFewins-Kalb** [comment]
It could go either way. The actions bit is an optional extra but it always case notes. I wasn't really sure how to classify it. I'm open to moving it to actions if'n you prefer.

**Comment by theVKC** [comment]
I'm wondering if we want to rebuild the script to *always* update? Would that be better functionality (part of the "let's make notes scripts do more stuff" movement)?

**Comment by RobertFewins-Kalb** [comment]
Umm...yes. I can withdraw the pull and make that upgrade.

**Comment by RobertFewins-Kalb** [comment]
Or I could just update the file I'm pulling...

**Comment by theVKC** [comment]
Please do! Although I am going to hold off on accepting it until Monday after script freeze. :)

**Comment by RobertFewins-Kalb** [comment]
Word

**Comment by theVKC** [comment]
@RobertFewins-Kalb: I'm going to close this. Can you re-pull as an actions script? Perhaps update the issue title to reflect that?

**Pull request closed without merging**
