### PR TITLE
Worker_sig update

### PR DESCRIPTION
**Pull request by CDPotter**
Do loop was still looking for worker_sig after it was changed to worker_signature

### CODE REVIEW

**Comment by CDPotter** [comment]
#927

**Comment by IlseFerris** [comment]
I also updated this in my pull requests as well, plus other updates.

**Comment by theVKC** [comment]
@IlseFerris, I'm going to take Charles' only for this, just to avoid a merge conflict.

**Comment by IlseFerris** [comment]
Works for me!

**Pull request merged**
