### PR TITLE
Resolves #1787 Create BANKED MONTH DATABASE UPDATER.vbs

### LINKED ISSUE #1787: New script - banked month database maintenance
This would be a utility that checks all cases in the access database.  It steps through all cases/members coded as using a banked month in the month selected, goes to ELIG/FS, finds the most recent approved version, and checks that the member remains active, if not, it reassigns the database value so that an accurate list can be submitted to DHS.
I propose calling it a UTILITY because it updates a database, not MAXIS, but would be open to BULK as well.  
Once I know where it belongs I will pull in my latest version, as well as a copy of the database table to insert into usage statistics.accdb.

### PR DESCRIPTION
**Pull request by courtrightd**
Blip: A utility to check and update the ABAWD Banked Month access database before submitting the monthly list.

### CODE REVIEW

**Comment by theVKC** [comment]
@courtrightd, a couple of things:

1. Can you update the utilities MAIN MENU with this?
2. Instructions for SIR?

**Comment by courtrightd** [comment]
Yes and yes, early next week.  I will get the database template up soon as well.

**Comment by theVKC** [comment]
Excellent. Thank you @courtrightd!

**Comment by theVKC** [comment]
Just noticed this:

image

Also, did you update the utilities main menu? I can swear I just saw you do it.

**Comment by theVKC** [comment]
(We need "UTILITIES - " at the beginning of the file name, @courtrightd)

**Comment by courtrightd** [comment]
File name fixed.  Yes, the utilities main menu was updated, you pulled it in yesterday I believe.  I may have still been feverish when submitting this stuff last week.

**Pull request merged**
