### PR TITLE
Reworking script to use excel, manual, and rept/actv

### PR DESCRIPTION
**Pull request by CDPotter**
BLIPs: 

CASE NOTE FROM LIST: Revamped/renamed (Case note from excel list) script can now case note in bulk from either manual entry, REPT/ACTV, in addition to the current functionally to use an excel spreadsheet of your choice

MEMO FROM LIST: New script to memo in bulk from either manual entry, REPT/ACTV, or an excel spreadsheet of your choice

TILK FROM LIST: Revamped/renamed (BULK TIKLER) script to TIKL in bulk from REPT/ACTV, or an excel spreadsheet of your choice, in addition to the current functionality of manually entering case numbers.

### CODE REVIEW

**Comment by CDPotter** [comment]
resolves #1569

**Comment by theVKC** [comment]
I'm really confused by your blip. Your blip says it "allows people", and talks about "this script", but this looks like you deleted and rebuilt two scripts, and added a third. Can you break your blip into how it affected each individual script?

**Comment by CDPotter** [comment]
Just in case it didn't notify, I edited the BLIPS

**Comment by theVKC** [comment]
Thanks @CDPotter! I'm going to wait until after next release. This could be big and I want to test it.

**Pull request merged**
