### PR TITLE
RESOLVES #1998 & #2083 Modernizing ACTIONS main menu/Remove Housing Grant FIATER

### LINKED ISSUE #1998: Update ACTIONS main menu to have the new look/feel
This will give me a chance to test my function, so I'll take it.

### PR DESCRIPTION
**Pull request by CDPotter**
BLIP: Menu has been reworked behind the scenes to better fit the standard set by BULK/NOTES/NOTICES. Housing Grant FIATER was also removed as MAXIS does it now.

### CODE REVIEW

**Comment by CDPotter** [comment]
I left in the split sections as commented out in case we need to use them at some point for something other than an alpha split.

**Comment by theVKC** [comment]
Can you also delete the FIATer source file in your branch, @CDPotter?

**Comment by CDPotter** [comment]
It is now deleted.

**Comment by theVKC** [comment]
Thank you!

**Pull request merged**
