### PR TITLE
Addresses #2061 Option to add supervisor to GA/RCA check

### LINKED ISSUE #2061: Enhancement Request -- Add supervisor name to BULK report scripts that can be run agency wide
A request has been made to add the supervisor name to BULK - CHECK SNAP FOR GA/RCA. For scripts like this, though, that can be used for quality assurance, I'm thinking we could expand that to other BULK report scripts to make distribution of lists easier.

I have a couple of ideas for this and would happy to take it on.

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
Blip: Script users are given the option to add the worker's supervisor to the script's output.

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
Titled the pull request "Addresses" because I intend to give other scripts a lookyloo to see if the issue is relevant to other bulk scripts.

**Comment by RobertFewins-Kalb** [comment]
Wait! It needs the new dialog.

**Comment by theVKC** [comment]
@RobertFewins-Kalb: should I wait until you complete the others? Or would you want me to pull this in now and then keep revisiting it throughout the month.

**Comment by RobertFewins-Kalb** [comment]
That's all I am going to be able to get done today. But I would like to keep poking throughout April.

**Comment by theVKC** [comment]
I will pull this when I pull the others, then, and then we can keep revisiting as we go. :)

**Pull request merged**
