### PR TITLE
Bugfix NOTES - EMPLOYMENT PLAN OR STATUS UPDATE.vbs

### PR DESCRIPTION
**Pull request by courtrightd**
Fixes case noting / dialog bug with Status update portion

### CODE REVIEW

**Comment by courtrightd** [comment]
#1000 !!!!  I win!!!!

**Comment by CDPotter** [comment]
confetti1

**Comment by IlseFerris** [comment]
YAYYYYY!

**Comment by theVKC** [comment]
image

**Comment by theVKC** [comment]
@courtrightd, was there an issue on this? If not, can you add one and tag it with this round issue number?

**Comment by courtrightd** [comment]
I already closed it, was #998.

**Pull request merged**
