### PR TITLE
Update to DOCS RECEIVED

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
(1) Updated the header to put the document received in the header
(2) Updated the url to allow for the BETA FuncLib

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
This should resolve #447

**Comment by theVKC** [comment]
Please try to remember to create branches when you are working an issue!!

**Comment by RobertFewins-Kalb** [comment]
Poop. Sorry. Should I close and try again?

**Comment by theVKC** [comment]
No. Want to update the functions for case noting though? new_line is out, variable is in.

**Comment by RobertFewins-Kalb** [comment]
Double poop. Not my finest hour.

**Pull request closed without merging**
