### PR TITLE
Create NOTES - ES REFERRAL.vbs

### LINKED ISSUE #997: New script - NOTES - ES REFERRAL
A case note template for use when referring someone to employment services. Includes fancy database - populated dropdowns for counties using the ES Database.  Currently in the project TPS REPORTS folder, I need to update for non-database counties and then move to main folder.

### PR DESCRIPTION
**Pull request by courtrightd**
Resolves #997 
Blip:  A new script for case noting when a worker refers an MFIP or DWP case to employment services.

### CODE REVIEW

**Comment by theVKC** [comment]
@courtrightd, can you amend your branch to also update the MAIN MENU script?

**Comment by courtrightd** [comment]
Oops – I can’t get to it till tomorrow, but it will be done.

**Comment by theVKC** [comment]
Good deal! Thanks @courtrightd!

**Comment by courtrightd** [comment]
@theVKC Main Menu button added, can now be merged.

**Pull request merged**
